### ISSUE TITLE
Add infinite effect duration

### ISSUE THREAD

**Issue by B1BU** [ChenCMD/MC-Datapack-Utility#72]
As of 1.19.4 you can set the duration of an effect to "infinite" but currently the extension gives an error if you do that

**Comment by B1BU** [comment]
Oh, sorry it's actually an issue with language-mcfunction

**Comment by ChenCMD** [comment]
There should be no code diagnosis in language-mcfunction either, so perhaps that is not the cause either.

**Comment by B1BU** [comment]
Actually it was Datapack Helper Plus, the version was set to 1.19.3. lol
